name: CI

on: [push, pull_request]

jobs:
  unit-test:
    name: unit tests
    runs-on: ubuntu-latest
    container:
      image: amutake/satysfi:latest
    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: |
          export HOME=/root
          eval $(opam env)
          satysfi --text-mode "text" test/main.test.saty -o main.txt
      - name: Check test results
        run: |
          cat main.txt | grep "0 fail"
      - name: Install Apt dependencies
        run: apt-get update && apt-get install -y xz-utils liblzma-dev
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: yabai2020w
          path: main.txt
